### ISSUE TITLE
Användare med rollen organizer kan inte skapa regattor

### ISSUE THREAD

**Issue by brstp** [24-timmarsseglingarna/giona#38]
Rapporterat av @mbj4668

**Comment by mbj4668** [comment]
Vi kan stänga denna.  Jag hittade inte var man skulle skapa regattor först.

**Comment by brstp** [comment]
Och det visar att skapandet ligger på fel ställe. ;-)

Den tis 17 apr. 2018 17:03Martin Bjorklund <notifications@github.com> skrev:
