### ISSUE TITLE
Presentation av redan påbörjade deltagaranmälningar ej intuitiv

### ISSUE THREAD

**Issue by brstp** [24-timmarsseglingarna/giona#45]
@mbj4668 :
![image](https://user-images.githubusercontent.com/454633/38869445-05486e04-424b-11e8-8aed-07e470b2c281.png)

**Comment by mbj4668** [comment]
Rubriken tyder på att den visar "redan påbörjade" anmälningar.  Men den verkar visa _alla_ anmälningar.

![image](https://user-images.githubusercontent.com/168146/38890779-ae49a216-4282-11e8-9d28-7249d34cd177.png)
