### ISSUE TITLE
Tom startperiod slut ger krash

### ISSUE THREAD

**Issue by mbj4668** [24-timmarsseglingarna/giona#52]
Jag försöker skapa en regatta med tom startperiodens slut, men då får man en krash.

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

Det sker ingen validering på att slutet är senare än början.

Överkurs kanske, men det vore snyggt om startperiodens slut inte hade dagens tid som default, utan startpersiodens början.

**Comment by brstp** [comment]
Jag behärskar inte javaacript tillräckligt för att fixa så att startperiodens slut sätts till samma som början.

https://jqueryui.com/datepicker/#date-range

**Comment by brstp** [comment]
Kan inte återskapa krasch med tom startperiodens slut på race.
@mbj4668

**Comment by mbj4668** [comment]
Gå till https://giona-dev.24-timmars.nu/races/7/edit

Där finns nu en startperiodens slut.  Gå till det fältet och blanka ut det.

Klicka på Spara.
