### ISSUE TITLE
Inför "statisk" information om APIt

### ISSUE THREAD

**Issue by mbj4668** [24-timmarsseglingarna/giona#54]
Inför en path tex /api/v1/info som returnerar en json-struktur med följande data:

    {
        "version": "<Major>.<Minor>.<Patch>",  // <Major> måste ändras vid icke-bakåtkompatibla ändringar
       "app-info" : { // info specifikt för appen
             "upgrade-text": "...",  // visas för användaren
             "require-upgrade": ["vsn", ...]
            ...
    }

**Comment by brstp** [comment]
Bra.

Börjar vi på 1.0.0 nu? Lite historieförfalskning men någonstans ska man börja. 

Är "upgrade-text" en generell text om att uppdatera i app-affären eller är den specifikt kopplad till versionen eller ändringarna som ligger i versionen?

Vad är "require-upgrade"?

Kan du kolla över vilka attribut som du använder? De som inte används nu plockar jag bort ur API:et. Då är det lättare att se om jag bryter kompabiliteten. Vill du sedan använda dem så lägger jag dit dem och är striktare med förändringar av dem.

**Comment by brstp** [comment]
Fundering ... 
Vill du att den ska ligga i den versionshanterade API-strukturen så att det finns en fil för varje major version? Eller en fil som ligger direkt under root?

Typ:
https://hostname.domain.name/api_version.json

Detta är enklare och renare

**Comment by mbj4668** [comment]
Den 21 april 2018 09:54 skrev Stefan Pettersson <notifications@github.com>:

> Bra.
>
> Börjar vi på 1.0.0 nu? Lite historieförfalskning men någonstans ska man
> börja.
>

Ja det tycker jag.


> Är "upgrade-text" en generell text om att uppdatera i app-affären eller är
> den specifikt kopplad till versionen eller ändringarna som ligger i
> versionen?
>
>
> Jag tänker mig generell text, men istället för att hårdkoda i appen så
ligger den på serversidan så att vi kan ändra vid behov.


> Vad är "require-upgrade"?
>

En lista på app-versioner, kanske med wildcard. Tanken är att om vi vet att
en viss version strular kan vi lägga in den i denna lista.

Jag tänker mig att vi börjar med detta, så fyller vi på när vi kommer på
mer.


> Kan du kolla över vilka attribut som du använder?
>

Du menar rent generellt i alla frågor jag ställer?  Det kan jag göra.

**Comment by mbj4668** [comment]
2018-04-21 11:06 GMT+02:00 Stefan Pettersson <notifications@github.com>:

> Fundering ...
> Vill du att den ska ligga i den versionshanterade API-strukturen så att
> det finns en fil för varje major version? Eller en fil som ligger direkt
> under root?
>
> Typ:
> https://hostname.domain.name/api_version.json
>
> Detta är enklare och renare
>

Det blir bra!

**Comment by brstp** [comment]
Då kommer filen att heta så. I applikationens filstruktur kommer den att ligga under /public/

Ja, generellt, alla attribut som appen frågar efter  och använder. Jag skickar med en massa attribut som jag initialt tänkte var viktiga men som ännu inte kommit till användning t.ex. team.dns, team.dnf. Jag rensar hellre bort dem och så definierar vi dem när appen behöver dem, eller jag erbjuder dem.
