### ISSUE TITLE
Handikapp, konstigt tillstånd

### ISSUE THREAD

**Issue by brstp** [24-timmarsseglingarna/giona#66]
Se över flödet med handikapp/byte handikapp

Från kommer att skaffa mätbrev. Sedan i märkligt tillstånd

![image](https://user-images.githubusercontent.com/454633/40276805-9f8a140e-5c13-11e8-95dd-6c7e9af7d290.png)

**Comment by mbj4668** [comment]
Kanske skall knappen "ange handikapp" tas bort?  går man via "nollställ" så fungerar det bra.  kanske byta namn från "nollställ' till "ändra"?

![image](https://user-images.githubusercontent.com/168146/40276825-1e12d662-5c14-11e8-9f83-0f236e6f4f58.png)
