### ISSUE TITLE
fel med handikapp

### ISSUE THREAD

**Issue by mbj4668** [24-timmarsseglingarna/giona#72]
om man i en anmälan väljer SXK-tal från tabell, men inte väljer något brev, och klickar Uppdatera direkt så fungerar det bra.  man borde hamna i samma läge som innan, dvs utan handikapp.

**Comment by mbj4668** [comment]
det blit också konstigt om man tex väljer SRS-tal enl tablle och sedan Tillbaka.  då tycker den att man har valt ett SXK-tal och man kan gå vidare.

**Comment by brstp** [comment]
Japp. Feldesignat. En rättning finns i nästa release.
