### ISSUE TITLE
Ansöka om och sätta SXK-tal

### ISSUE THREAD

**Issue by brstp** [24-timmarsseglingarna/giona#78]
Deltagare fyller i de mått som behövs för att utfärda SXK-tal för en båt. 

Användare med behörighet (SXK-talsgruppen) kan granska, ändra ingångsvärden, se med formel beräknat respittal och sedan sätta respittal (SXK-tal) och godkänna värdet för användning.

Bäst-före-datum ska hanteras (så att uppdaterade mätetal gör att äldre inte värden inte längre kan användas för nya seglingar).

Indata ska vara synliga för deltagare men inte formler, mellanled och maskinellt beräknat respittal.

**Comment by mbj4668** [comment]
Detta sker nu i separat system, Giona kan nu importera från detta.
